### ISSUE TITLE
Downloading/updating jsons without saving images is extremely slow

### ISSUE THREAD

**Issue by themaneiac** [Sibusten/derpibooru-downloader#18]
When I create a task to only update jsons it updates about 1 per second. Things are really fast if I have it download both images and jsons, though. If there is an easy fix that would be great. 😄 
It would keep my tasks from downloading images at the same time at a couple points each day (which might cause corruption).
It does this in both the GUI and CMD versions.

**Comment by Sibusten** [comment]
What settings are you using to have it not download images? I hadn't considered having the program not download images, so there wasn't an option to disable that.

**Comment by themaneiac** [comment]
![image](https://user-images.githubusercontent.com/6430050/54898804-d35c3680-4e8a-11e9-9590-24338cd57f01.png)

**Comment by Sibusten** [comment]
I believe it is taking a long time because the program is downloading each image, since the image path is invalid and it can't confirm if that file already exists.

I added a new option to prevent image downloading called "Save Json Only", which should do what you want. See [v1.4.2](https://github.com/Sibusten/derpibooru-downloader/releases/tag/v1.4.2)
