### ISSUE TITLE
Only downloading first page of images

### ISSUE THREAD

**Issue by derpynirvash** [Sibusten/derpibooru-downloader#40]
I am using version 2.0.0 and have tried with both the GUI and CMD line options. The downloader will get stuck repetitively trying to download the first page of images. If I stop the download and change the 'Start page', to 2, it will then download only the second page and again get stuck looping through those images.

**Comment by Sibusten** [comment]
I am using v2.0.0 and can not reproduce this issue. What are the settings you are using?

**Comment by derpynirvash** [comment]
After doing some more testing, it seems that the || operator in the search field is causing this bug. I did use a search previously with || in v1.4.1 without issue. 

Reproduction steps: 
Using a freshly download and extracted copy of v2.0.0, I entered my API key, and used the search "applejack || rainbowdash" and then started downloading. Although in this case it downloaded 96 images before bugging out and repeating. 

![image](https://user-images.githubusercontent.com/4786654/86492072-778d8800-bd32-11ea-8925-9b36a84ce131.png)

**Comment by Sibusten** [comment]
You're right, the `||` is what is causing the issue. The way paging works was changed to help performance, but operator precedence wasn't considered in modifying the search term.

I will have a new release with a fix for this, but if you want to use it now it can be fixed by wrapping the search in parenthesis: `(applejack || rainbowdash)`

**Comment by Sibusten** [comment]
New release is up: [v2.0.1](https://github.com/Sibusten/derpibooru-downloader/releases/tag/v2.0.1)

Thanks for the report!
